name: release legacy

on:
  push:
    tags:
      - "v*-legacy"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: "Build release apk"
        run: ./gradlew assembleRelease --stacktrace

      - name: "Sign release"
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: "Rename archive"
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app-release.apk

      - name: "Create GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
          fail_on_unmatched_files: true